# Generated by Django 5.2.1 on 2025-05-10 14:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tour_name', models.CharField(default='Экскурсия', max_length=300)),
                ('tour_desc', models.TextField(default='Описание экскурсии', max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='UserStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_bonus_currency', models.IntegerField()),
                ('user_promocode', models.CharField(max_length=20)),
                ('user_own_tours', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='startpage.tour')),
                ('user_stats_to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
